#!/bin/sh

./start
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start JOSSO: $status"
  exit $status
fi

while sleep 60; do
  ps aux | grep java |grep -q -v grep
  JOSSO_STATUS=$?

  if [ $JOSSO_STATUS -ne 0 ]; then
    echo "JOSSO processes has already exited."
    exit 1
  fi
done